"use client";

import { useState } from "react";
import { Watch, Copy, Check, Loader2, ClipboardList } from "lucide-react";
import {
  Button,
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui";
import { cn } from "@/lib/utils";
import { createClient } from "@/lib/supabase/client";
import { toast } from "sonner";

interface GarminNutritionExportProps {
  racePlanId: string;
  raceName: string;
  goalTimeMinutes: number;
  startTime: string;
  className?: string;
}

interface HourData {
  hourNumber: number;
  clockTime: string;
  products: Array<{
    name: string;
    brand: string;
    quantity: number;
  }>;
}

function calculateClockTime(startTime: string, hourIndex: number): string {
  const parts = startTime.split(":").map(Number);
  const startHour = parts[0] ?? 6;
  const startMinute = parts[1] ?? 0;
  const totalMinutes = startHour * 60 + startMinute + hourIndex * 60;
  const hours = Math.floor(totalMinutes / 60) % 24;
  const period = hours >= 12 ? "PM" : "AM";
  const displayHour = hours % 12 || 12;
  return `${displayHour}${period}`;
}

export function GarminNutritionExport({
  racePlanId,
  raceName,
  goalTimeMinutes,
  startTime,
  className,
}: GarminNutritionExportProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [hourData, setHourData] = useState<HourData[] | null>(null);
  const [copiedField, setCopiedField] = useState<number | null>(null);

  const totalHours = Math.ceil(goalTimeMinutes / 60);

  const loadNutritionData = async () => {
    setLoading(true);
    try {
      const supabase = createClient();

      // First, load all nutrition products to create a lookup map
      const { data: allProducts } = await supabase
        .from("nutrition_products")
        .select("id, brand, name")
        .eq("is_active", true);

      const productMap = new Map(
        (allProducts || []).map((p) => [p.id, p])
      );

      // Fetch nutrition plan with items (without nested product join)
      const { data: plan } = await supabase
        .from("race_nutrition_plans")
        .select(`
          id,
          race_nutrition_plan_items (
            product_id,
            hour_number,
            quantity
          )
        `)
        .eq("race_plan_id", racePlanId)
        .single();

      if (!plan) {
        setHourData([]);
        setLoading(false);
        return;
      }

      const hours: HourData[] = [];

      for (let i = 0; i < totalHours; i++) {
        const hourNumber = i + 1;
        const hourItems = (plan.race_nutrition_plan_items || []).filter(
          (item: { hour_number: number }) => item.hour_number === hourNumber
        );

        const products = hourItems.map((item: {
          product_id: string;
          quantity: number;
        }) => {
          const product = productMap.get(item.product_id);
          return {
            name: product?.name || "Unknown",
            brand: product?.brand || "",
            quantity: item.quantity || 1,
          };
        });

        hours.push({
          hourNumber,
          clockTime: calculateClockTime(startTime, i),
          products,
        });
      }

      setHourData(hours);
    } catch (err) {
      console.error("Error loading nutrition data:", err);
      setHourData([]);
    }
    setLoading(false);
  };

  const handleOpen = async () => {
    setIsOpen(true);
    await loadNutritionData();
  };

  const formatHourForGarmin = (hour: HourData): string => {
    if (hour.products.length === 0) {
      return `H${hour.hourNumber} (${hour.clockTime}): Water/Rest`;
    }

    const productList = hour.products
      .map(p => p.quantity > 1 ? `${p.quantity}x ${p.brand} ${p.name}` : `${p.brand} ${p.name}`)
      .join(", ");

    return `H${hour.hourNumber} (${hour.clockTime}): ${productList}`;
  };

  const copyToClipboard = async (text: string, index: number) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedField(index);
      toast.success("Copied to clipboard");
      setTimeout(() => setCopiedField(null), 2000);
    } catch {
      toast.error("Failed to copy");
    }
  };

  const copyAllToClipboard = async () => {
    if (!hourData) return;

    const allText = [
      `${raceName} - Nutrition Plan`,
      "═".repeat(30),
      "",
      ...hourData.map(formatHourForGarmin),
      "",
      "Generated by FinalClimb",
    ].join("\n");

    try {
      await navigator.clipboard.writeText(allText);
      toast.success("All hours copied to clipboard");
    } catch {
      toast.error("Failed to copy");
    }
  };

  return (
    <>
      <Button
        variant="outline"
        onClick={handleOpen}
        className={cn("gap-2", className)}
        disabled={!goalTimeMinutes}
      >
        <Watch className="h-4 w-4" />
        Garmin Text Fields
      </Button>

      <Dialog open={isOpen} onOpenChange={setIsOpen}>
        <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Watch className="h-5 w-5 text-emerald-500" />
              Garmin Nutrition Text Fields
            </DialogTitle>
            <DialogDescription>
              Copy these text strings to use as custom data fields or notes on your Garmin device.
            </DialogDescription>
          </DialogHeader>

          {loading ? (
            <div className="flex items-center justify-center py-8">
              <Loader2 className="h-6 w-6 animate-spin text-brand-sky-500" />
              <span className="ml-2 text-brand-navy-600">Loading nutrition plan...</span>
            </div>
          ) : !hourData || hourData.length === 0 ? (
            <div className="py-8 text-center">
              <ClipboardList className="h-12 w-12 text-brand-navy-300 mx-auto mb-3" />
              <p className="text-brand-navy-600 font-medium">No nutrition plan found</p>
              <p className="text-sm text-brand-navy-500 mt-1">
                Add products to your nutrition timeline first
              </p>
            </div>
          ) : (
            <div className="space-y-4 py-2">
              {/* Instructions */}
              <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-lg text-sm text-emerald-800">
                <p className="font-medium mb-1">How to use:</p>
                <ol className="list-decimal list-inside space-y-1 text-emerald-700">
                  <li>Copy individual hours or the full plan</li>
                  <li>Add to Garmin Connect notes or custom text fields</li>
                  <li>View on your watch during the race</li>
                </ol>
              </div>

              {/* Copy All Button */}
              <Button
                variant="outline"
                onClick={copyAllToClipboard}
                className="w-full gap-2"
              >
                <Copy className="h-4 w-4" />
                Copy All Hours
              </Button>

              {/* Hour-by-hour text fields */}
              <div className="space-y-2 max-h-64 overflow-y-auto">
                {hourData.map((hour, index) => {
                  const text = formatHourForGarmin(hour);
                  const isCopied = copiedField === index;

                  return (
                    <div
                      key={hour.hourNumber}
                      className={cn(
                        "flex items-center gap-2 p-2 rounded-lg border",
                        hour.products.length > 0
                          ? "bg-white border-brand-navy-200"
                          : "bg-brand-navy-50 border-brand-navy-100"
                      )}
                    >
                      <div className={cn(
                        "w-8 h-8 rounded-lg flex items-center justify-center font-bold text-sm flex-shrink-0",
                        hour.products.length > 0
                          ? "bg-brand-sky-500 text-white"
                          : "bg-brand-navy-200 text-brand-navy-500"
                      )}>
                        {hour.hourNumber}
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm text-brand-navy-800 truncate font-mono">
                          {text}
                        </p>
                      </div>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => copyToClipboard(text, index)}
                        className="flex-shrink-0"
                      >
                        {isCopied ? (
                          <Check className="h-4 w-4 text-emerald-500" />
                        ) : (
                          <Copy className="h-4 w-4" />
                        )}
                      </Button>
                    </div>
                  );
                })}
              </div>

              {/* Tip */}
              <p className="text-xs text-brand-navy-500">
                Tip: For long races, copy 2-3 hours at a time to fit within Garmin&apos;s text limits.
              </p>
            </div>
          )}

          {/* Actions */}
          <div className="flex gap-3 pt-2">
            <Button
              variant="outline"
              onClick={() => setIsOpen(false)}
              className="flex-1"
            >
              Close
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
